on:
  push:
  workflow_dispatch:

jobs:
  deps:
    strategy:
      matrix:
        os: [ubuntu-22.04-arm, ubuntu-22.04-arm-dennis]
    runs-on: ${{ matrix.os }}
    steps:
      - run: npx envinfo
      - run: env
      - name: Install dependencies
        shell: bash
        run: |
          sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream && sudo apt-get update && sudo apt-get install -y protobuf-compiler libpulse-dev libpulse0 pipewire && systemctl --user daemon-reload && systemctl --user --now enable pipewire pipewire-pulse
      - if: failure()
        name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
